In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 100)

In [ ]:
from google.colab import files

uploaded = files.upload()

file_name = next(iter(uploaded))
print("Uploaded file:", file_name)

Saving Book2.xlsx to Book2 (2).xlsx
Uploaded file: Book2 (2).xlsx

In [ ]:
excel_file = pd.ExcelFile(file_name)

print("Sheets available in the workbook:")
for sheet in excel_file.sheet_names:
    print("-", sheet)

Sheets available in the workbook:
- Calendar
- Customer
- Discounts
- Product Category
- Product
- Product Subcategory
- Returns
- Sheet11
- Sales Data 2020
- Sales Data 2021
- Sales Data 2022
- Territory

In [ ]:
customer = pd.read_excel(file_name, sheet_name="Customer")
product = pd.read_excel(file_name, sheet_name="Product")
sales_2020 = pd.read_excel(file_name, sheet_name="Sales Data 2020")
sales_2021 = pd.read_excel(file_name, sheet_name="Sales Data 2021")
sales_2022 = pd.read_excel(file_name, sheet_name="Sales Data 2022")
returns = pd.read_excel(file_name, sheet_name="Returns")
territory = pd.read_excel(file_name, sheet_name="Territory ")

print("Customer:", customer.shape)
print("Product:", product.shape)
print("Sales 2020:", sales_2020.shape)
print("Sales 2021:", sales_2021.shape)
print("Sales 2022:", sales_2022.shape)
print("Returns:", returns.shape)
print("Territory:", territory.shape)

Customer: (18148, 13)
Product: (293, 11)
Sales 2020: (2630, 8)
Sales 2021: (23935, 8)
Sales 2022: (29481, 8)
Returns: (1809, 4)
Territory: (10, 4)

In [ ]:
customer.head()

,CustomerKey,Prefix,FirstName,LastName,BirthDate,MaritalStatus,Gender,EmailAddress,AnnualIncome,TotalChildren,EducationLevel,Occupation,HomeOwner
0,11000,MR.,JON,YANG,1966-04-08,M,M,jon24@adventure-works.com,90000,2,Bachelors,Professional,Y
1,11001,MR.,EUGENE,HUANG,1965-05-14,S,M,eugene10@adventure-works.com,60000,3,Bachelors,Professional,N
2,11002,MR.,RUBEN,TORRES,1965-08-12,M,M,ruben35@adventure-works.com,60000,3,Bachelors,Professional,Y
3,11003,MS.,CHRISTY,ZHU,1968-02-15,S,F,christy12@adventure-works.com,70000,0,Bachelors,Professional,N
4,11004,MRS.,ELIZABETH,JOHNSON,1968-08-08,S,F,elizabeth5@adventure-works.com,80000,5,Bachelors,Professional,Y

In [ ]:
product.head()

,ProductKey,ProductSubcategoryKey,ProductSKU,ProductName,ModelName,ProductDescription,ProductColor,ProductSize,ProductStyle,ProductCost,ProductPrice
0,214,31,HL-U509-R,"Sport-100 Helmet, Red",Sport-100,"Universal fit, well-vented, lightweight , snap...",Red,0,0,13.0863,34.9900
1,215,31,HL-U509,"Sport-100 Helmet, Black",Sport-100,"Universal fit, well-vented, lightweight , snap...",Black,0,0,12.0278,33.6442
2,218,23,SO-B909-M,"Mountain Bike Socks, M",Mountain Bike Socks,Combination of natural and synthetic fibers st...,White,M,U,3.3963,9.5000
3,219,23,SO-B909-L,"Mountain Bike Socks, L",Mountain Bike Socks,Combination of natural and synthetic fibers st...,White,L,U,3.3963,9.5000
4,220,31,HL-U509-B,"Sport-100 Helmet, Blue",Sport-100,"Universal fit, well-vented, lightweight , snap...",Blue,0,0,12.0278,33.6442

In [ ]:
sales_2020.head()

,OrderDate,StockDate,OrderNumber,ProductKey,CustomerKey,TerritoryKey,OrderLineItem,OrderQuantity
0,2020-01-01,2019-09-21,SO45080,332,14657,1,1,1
1,2020-01-01,2019-12-05,SO45079,312,29255,4,1,1
2,2020-01-01,2019-10-29,SO45082,350,11455,9,1,1
3,2020-01-01,2019-11-16,SO45081,338,26782,6,1,1
4,2020-01-02,2019-12-15,SO45083,312,14947,10,1,1

In [ ]:
sales_2021.head()

,C,StockDate,OrderNumber,ProductKey,CustomerKey,TerritoryKey,OrderLineItem,OrderQuantity
0,2021-01-01,2020-10-17,SO48797,385,14335,1,1,1
1,2021-01-01,2020-09-30,SO48802,383,24923,9,1,1
2,2021-01-01,2020-11-29,SO48801,326,15493,1,1,1
3,2021-01-01,2020-11-16,SO48799,352,26708,4,1,1
4,2021-01-01,2020-12-16,SO48798,369,23332,9,1,1

In [ ]:
sales_2022.head()

,OrderDate,StockDate,OrderNumber,ProductKey,CustomerKey,TerritoryKey,OrderLineItem,OrderQuantity
0,2022-01-01,2021-12-13,SO61285,529,23791,1,2,2
1,2022-01-01,2021-09-24,SO61285,214,23791,1,3,1
2,2022-01-01,2021-09-04,SO61285,540,23791,1,1,1
3,2022-01-01,2021-09-28,SO61301,529,16747,1,2,2
4,2022-01-01,2021-10-21,SO61301,377,16747,1,1,1

In [ ]:
returns.head()

  ReturnDate  TerritoryKey  ProductKey  ReturnQuantity
0 2020-01-18             9         312               1
1 2020-01-18            10         310               1
2 2020-01-21             8         346               1
3 2020-01-22             4         311               1
4 2020-02-02             6         312               1

In [ ]:
territory.head()

         Region        Country      Continent
0  1  Northwest  United States  North America
1  2  Northeast  United States  North America
2  3    Central  United States  North America
3  4  Southwest  United States  North America
4  5  Southeast  United States  North America

In [ ]:
sales_2022.tail()

,OrderDate,StockDate,OrderNumber,ProductKey,CustomerKey,TerritoryKey,OrderLineItem,OrderQuantity
29476,2022-06-30,2022-03-22,SO74143,477,28517,10,3,2
29477,2022-06-30,2022-03-15,SO74143,479,28517,10,2,1
29478,2022-06-30,2022-04-08,SO74143,606,28517,10,1,1
29479,2022-06-30,2022-05-15,SO74124,480,21676,7,2,2
29480,2022-06-30,2022-05-04,SO74124,538,21676,7,1,2

In [ ]:
print("Customer:", customer.shape)
print("Product:", product.shape)
print("Sales 2020:", sales_2020.shape)
print("Sales 2021:", sales_2021.shape)
print("Sales 2022:", sales_2022.shape)

Customer: (18148, 13)
Product: (293, 11)
Sales 2020: (2630, 8)
Sales 2021: (23935, 8)
Sales 2022: (29481, 8)

In [ ]:
print("Returns:", returns.shape)
print("Territory:", territory.shape)
print("Customer:", customer.shape)

Returns: (1809, 4)
Territory: (10, 4)
Customer: (18148, 13)

In [ ]:
print("Customer columns:")
print(customer.columns.tolist())

print("\nProduct columns:")
print(product.columns.tolist())

print("\nSales 2020 columns:")
print(sales_2020.columns.tolist())

In [ ]:
product.dtypes

ProductKey                 int64
ProductSubcategoryKey      int64
ProductSKU                object
ProductName               object
ModelName                 object
ProductDescription        object
ProductColor              object
ProductSize               object
ProductStyle              object
ProductCost              float64
ProductPrice             float64
dtype: object

In [ ]:
product.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 293 entries, 0 to 292
Data columns (total 11 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   ProductKey             293 non-null    int64
 1   ProductSubcategoryKey  293 non-null    int64
 2   ProductSKU             293 non-null    object
 3   ProductName            293 non-null    object
 4   ModelName              293 non-null    object
 5   ProductDescription     293 non-null    object
 6   ProductColor           243 non-null    object
 7   ProductSize            293 non-null    object
 8   ProductStyle           293 non-null    object
 9   ProductCost            293 non-null    float64
 10  ProductPrice           293 non-null    float64
dtypes: float64(2), int64(2), object(7)
memory usage: 25.3+ KB

In [ ]:
customer.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18148 entries, 0 to 18147
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   CustomerKey     18148 non-null  int64
 1   Prefix          18018 non-null  object
 2   FirstName       18148 non-null  object
 3   LastName        18148 non-null  object
 4   BirthDate       18148 non-null  datetime64[ns]
 5   MaritalStatus   18148 non-null  object
 6   Gender          18018 non-null  object
 7   EmailAddress    18148 non-null  object
 8   AnnualIncome    18148 non-null  int64
 9   TotalChildren   18148 non-null  int64
 10  EducationLevel  18148 non-null  object
 11  Occupation      18148 non-null  object
 12  HomeOwner       18148 non-null  object
dtypes: datetime64[ns](1), int64(3), object(9)
memory usage: 1.8+ MB

In [ ]:
sales_2020.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2630 entries, 0 to 2629
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   OrderDate      2630 non-null   datetime64[ns]
 1   StockDate      2630 non-null   datetime64[ns]
 2   OrderNumber    2630 non-null   object
 3   ProductKey     2630 non-null   int64
 4   CustomerKey    2630 non-null   int64
 5   TerritoryKey   2630 non-null   int64
 6   OrderLineItem  2630 non-null   int64
 7   OrderQuantity  2630 non-null   int64
dtypes: datetime64[ns](2), int64(5), object(1)
memory usage: 164.5+ KB

In [ ]:
sales_2021.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23935 entries, 0 to 23934
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   C              23935 non-null  datetime64[ns]
 1   StockDate      23935 non-null  datetime64[ns]
 2   OrderNumber    23935 non-null  object
 3   ProductKey     23935 non-null  int64
 4   CustomerKey    23935 non-null  int64
 5   TerritoryKey   23935 non-null  int64
 6   OrderLineItem  23935 non-null  int64
 7   OrderQuantity  23935 non-null  int64
dtypes: datetime64[ns](2), int64(5), object(1)
memory usage: 1.5+ MB

In [ ]:
sales_2022.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29481 entries, 0 to 29480
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   OrderDate      29481 non-null  datetime64[ns]
 1   StockDate      29481 non-null  datetime64[ns]
 2   OrderNumber    29481 non-null  object
 3   ProductKey     29481 non-null  int64
 4   CustomerKey    29481 non-null  int64
 5   TerritoryKey   29481 non-null  int64
 6   OrderLineItem  29481 non-null  int64
 7   OrderQuantity  29481 non-null  int64
dtypes: datetime64[ns](2), int64(5), object(1)
memory usage: 1.8+ MB

In [ ]:
returns.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1809 entries, 0 to 1808
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   ReturnDate      1809 non-null   datetime64[ns]
 1   TerritoryKey    1809 non-null   int64
 2   ProductKey      1809 non-null   int64
 3   ReturnQuantity  1809 non-null   int64
dtypes: datetime64[ns](1), int64(3)
memory usage: 56.7 KB

In [ ]:
customer.isnull().sum()

CustomerKey         0
Prefix            130
FirstName           0
LastName            0
BirthDate           0
MaritalStatus       0
Gender            130
EmailAddress        0
AnnualIncome        0
TotalChildren       0
EducationLevel      0
Occupation          0
HomeOwner           0
dtype: int64

In [ ]:
product.isnull().sum()

ProductKey                0
ProductSubcategoryKey     0
ProductSKU                0
ProductName               0
ModelName                 0
ProductDescription        0
ProductColor             50
ProductSize               0
ProductStyle              0
ProductCost               0
ProductPrice              0
dtype: int64

In [ ]:
sales_2020.isnull().sum()

OrderDate        0
StockDate        0
OrderNumber      0
ProductKey       0
CustomerKey      0
TerritoryKey     0
OrderLineItem    0
OrderQuantity    0
dtype: int64

In [ ]:
sales_2021.isnull().sum()

C                0
StockDate        0
OrderNumber      0
ProductKey       0
CustomerKey      0
TerritoryKey     0
OrderLineItem    0
OrderQuantity    0
dtype: int64

In [ ]:
sales_2022.isnull().sum()

OrderDate        0
StockDate        0
OrderNumber      0
ProductKey       0
CustomerKey      0
TerritoryKey     0
OrderLineItem    0
OrderQuantity    0
dtype: int64

In [ ]:
returns.isnull().sum()

ReturnDate        0
TerritoryKey      0
ProductKey        0
ReturnQuantity    0
dtype: int64

In [ ]:
print("Duplicate rows in Customer:", customer.duplicated().sum())
print("Duplicate rows in Product:", product.duplicated().sum())
print("Duplicate rows in Sales 2020:", sales_2020.duplicated().sum())

Duplicate rows in Customer: 0
Duplicate rows in Product: 0
Duplicate rows in Sales 2020: 0

In [ ]:
print(sales_2021.columns.tolist())

['C', 'StockDate', 'OrderNumber', 'ProductKey', 'CustomerKey', 'TerritoryKey', 'OrderLineItem', 'OrderQuantity']

In [ ]:
sales_2021 = sales_2021.rename(columns={"C": "OrderDate"})

print(sales_2021.columns.tolist())

['OrderDate', 'StockDate', 'OrderNumber', 'ProductKey', 'CustomerKey', 'TerritoryKey', 'OrderLineItem', 'OrderQuantity']

In [ ]:
sales_2021["OrderDate"] = pd.to_datetime(sales_2021["OrderDate"], errors="coerce")

print(sales_2021["OrderDate"].dtype)
print(sales_2021["OrderDate"].head())

datetime64[ns]
0   2021-01-01
1   2021-01-01
2   2021-01-01
3   2021-01-01
4   2021-01-01
Name: OrderDate, dtype: datetime64[ns]

In [ ]:
sales_2020["OrderDate"] = pd.to_datetime(sales_2020["OrderDate"], errors="coerce")
sales_2022["OrderDate"] = pd.to_datetime(sales_2022["OrderDate"], errors="coerce")
returns["ReturnDate"] = pd.to_datetime(returns["ReturnDate"], errors="coerce")

print("Sales 2020:", sales_2020["OrderDate"].dtype)
print("Sales 2021:", sales_2021["OrderDate"].dtype)
print("Sales 2022:", sales_2022["OrderDate"].dtype)
print("Returns:", returns["ReturnDate"].dtype)

Sales 2020: datetime64[ns]
Sales 2021: datetime64[ns]
Sales 2022: datetime64[ns]
Returns: datetime64[ns]

In [ ]:
print("Invalid Sales 2020 dates:", sales_2020["OrderDate"].isna().sum())
print("Invalid Sales 2021 dates:", sales_2021["OrderDate"].isna().sum())
print("Invalid Sales 2022 dates:", sales_2022["OrderDate"].isna().sum())
print("Invalid Return dates:", returns["ReturnDate"].isna().sum())

Invalid Sales 2020 dates: 0
Invalid Sales 2021 dates: 0
Invalid Sales 2022 dates: 0
Invalid Return dates: 0

In [ ]:
high_price_products = product[product["ProductPrice"] > 1000]

high_price_products.head()

,ProductKey,ProductSubcategoryKey,ProductSKU,ProductName,ModelName,ProductDescription,ProductColor,ProductSize,ProductStyle,ProductCost,ProductPrice
10,238,14,FR-R92R-62,"HL Road Frame - Red, 62",HL Road Frame,Our lightest and best quality aluminum frame m...,Red,62,U,747.9682,1263.4598
11,241,14,FR-R92R-44,"HL Road Frame - Red, 44",HL Road Frame,Our lightest and best quality aluminum frame m...,Red,44,U,747.9682,1263.4598
12,244,14,FR-R92R-48,"HL Road Frame - Red, 48",HL Road Frame,Our lightest and best quality aluminum frame m...,Red,48,U,747.9682,1263.4598
13,247,14,FR-R92R-52,"HL Road Frame - Red, 52",HL Road Frame,Our lightest and best quality aluminum frame m...,Red,52,U,747.9682,1263.4598
14,250,14,FR-R92R-56,"HL Road Frame - Red, 56",HL Road Frame,Our lightest and best quality aluminum frame m...,Red,56,U,747.9682,1263.4598

In [ ]:
high_income_customers = customer[customer["AnnualIncome"] > 100000]

high_income_customers.head()

,CustomerKey,Prefix,FirstName,LastName,BirthDate,MaritalStatus,Gender,EmailAddress,AnnualIncome,TotalChildren,EducationLevel,Occupation,HomeOwner
78,11079,MR.,DONALD,GONZALEZ,1959-03-11,S,M,donald20@adventure-works.com,160000,0,Graduate Degree,Management,Y
79,11080,MR.,DAMIEN,CHANDER,1959-07-17,M,M,damien32@adventure-works.com,170000,0,Graduate Degree,Management,Y
80,11081,MRS.,SAVANNAH,BAKER,1966-07-24,M,F,savannah39@adventure-works.com,120000,2,Bachelors,Management,Y
81,11082,NaN,ANGELA,BUTLER,1966-08-04,S,NaN,angela17@adventure-works.com,130000,0,Graduate Degree,Management,N
82,11083,MS.,ALYSSA,COX,1966-03-15,M,F,alyssa37@adventure-works.com,130000,0,Graduate Degree,Management,Y

In [ ]:
large_quantity_orders = sales_2022[sales_2022["OrderQuantity"] > 5]

large_quantity_orders.head()

Empty DataFrame
Columns: [OrderDate, StockDate, OrderNumber, ProductKey, CustomerKey, TerritoryKey, OrderLineItem, OrderQuantity]
Index: []

In [ ]:
selected_occupations = customer[
    (customer["Occupation"] == "Professional") |
    (customer["Occupation"] == "Management")
]

selected_occupations.head()

,CustomerKey,Prefix,FirstName,LastName,BirthDate,MaritalStatus,Gender,EmailAddress,AnnualIncome,TotalChildren,EducationLevel,Occupation,HomeOwner
0,11000,MR.,JON,YANG,1966-04-08,M,M,jon24@adventure-works.com,90000,2,Bachelors,Professional,Y
1,11001,MR.,EUGENE,HUANG,1965-05-14,S,M,eugene10@adventure-works.com,60000,3,Bachelors,Professional,N
2,11002,MR.,RUBEN,TORRES,1965-08-12,M,M,ruben35@adventure-works.com,60000,3,Bachelors,Professional,Y
3,11003,MS.,CHRISTY,ZHU,1968-02-15,S,F,christy12@adventure-works.com,70000,0,Bachelors,Professional,N
4,11004,MRS.,ELIZABETH,JOHNSON,1968-08-08,S,F,elizabeth5@adventure-works.com,80000,5,Bachelors,Professional,Y

In [ ]:
red_products = product[product["ProductColor"] == "Red"]

red_products[["ProductName", "ProductColor", "ProductPrice"]].head()

                ProductName ProductColor  ProductPrice
0     Sport-100 Helmet, Red          Red       34.9900
10  HL Road Frame - Red, 62          Red     1263.4598
11  HL Road Frame - Red, 44          Red     1263.4598
12  HL Road Frame - Red, 48          Red     1263.4598
13  HL Road Frame - Red, 52          Red     1263.4598

In [ ]:
high_price_products = product[product["ProductPrice"] > 500]
high_price_products.head()

,ProductKey,ProductSubcategoryKey,ProductSKU,ProductName,ModelName,ProductDescription,ProductColor,ProductSize,ProductStyle,ProductCost,ProductPrice
10,238,14,FR-R92R-62,"HL Road Frame - Red, 62",HL Road Frame,Our lightest and best quality aluminum frame m...,Red,62,U,747.9682,1263.4598
11,241,14,FR-R92R-44,"HL Road Frame - Red, 44",HL Road Frame,Our lightest and best quality aluminum frame m...,Red,44,U,747.9682,1263.4598
12,244,14,FR-R92R-48,"HL Road Frame - Red, 48",HL Road Frame,Our lightest and best quality aluminum frame m...,Red,48,U,747.9682,1263.4598
13,247,14,FR-R92R-52,"HL Road Frame - Red, 52",HL Road Frame,Our lightest and best quality aluminum frame m...,Red,52,U,747.9682,1263.4598
14,250,14,FR-R92R-56,"HL Road Frame - Red, 56",HL Road Frame,Our lightest and best quality aluminum frame m...,Red,56,U,747.9682,1263.4598

In [ ]:
high_income_customers = customer[customer["AnnualIncome"] < 50000]

high_income_customers.head()

,CustomerKey,Prefix,FirstName,LastName,BirthDate,MaritalStatus,Gender,EmailAddress,AnnualIncome,TotalChildren,EducationLevel,Occupation,HomeOwner
14,11015,MS.,CHLOE,YOUNG,1979-02-27,S,F,chloe23@adventure-works.com,30000,0,Partial College,Skilled Manual,N
15,11016,MR.,WYATT,HILL,1979-04-28,M,M,wyatt32@adventure-works.com,30000,0,Partial College,Skilled Manual,Y
16,11017,MRS.,SHANNON,WANG,1944-06-26,S,F,shannon1@adventure-works.com,20000,4,High School,Skilled Manual,Y
17,11018,MR.,CLARENCE,RAI,1944-10-09,S,M,clarence32@adventure-works.com,30000,2,Partial College,Clerical,Y
18,11019,MR.,LUKE,LAL,1978-03-07,S,M,luke18@adventure-works.com,40000,0,High School,Skilled Manual,N

In [ ]:
large_quantity_orders = sales_2022[sales_2022["OrderQuantity"] > 3]

large_quantity_orders.head()

Empty DataFrame
Columns: [OrderDate, StockDate, OrderNumber, ProductKey, CustomerKey, TerritoryKey, OrderLineItem, OrderQuantity]
Index: []

In [ ]:
females = customer[customer["Gender"] == "F"]

females.head()

,CustomerKey,Prefix,FirstName,LastName,BirthDate,MaritalStatus,Gender,EmailAddress,AnnualIncome,TotalChildren,EducationLevel,Occupation,HomeOwner
3,11003,MS.,CHRISTY,ZHU,1968-02-15,S,F,christy12@adventure-works.com,70000,0,Bachelors,Professional,N
4,11004,MRS.,ELIZABETH,JOHNSON,1968-08-08,S,F,elizabeth5@adventure-works.com,80000,5,Bachelors,Professional,Y
7,11008,MRS.,ROBIN,VERHOFF,1964-07-07,S,F,rob4@adventure-works.com,60000,4,Bachelors,Professional,Y
9,11010,MS.,JACQUELYN,SUAREZ,1964-02-06,S,F,jacquelyn20@adventure-works.com,70000,0,Bachelors,Professional,N
11,11012,MRS.,LAUREN,WALKER,1968-01-18,M,F,lauren41@adventure-works.com,100000,2,Bachelors,Management,Y

In [ ]:
black_products = product[product["ProductColor"] == "Black"]

black_products[["ProductName", "ProductColor", "ProductPrice"]].head()

                  ProductName ProductColor  ProductPrice
1     Sport-100 Helmet, Black        Black       33.6442
15  LL Road Frame - Black, 58        Black      297.6346
16  LL Road Frame - Black, 60        Black      297.6346
17  LL Road Frame - Black, 62        Black      297.6346
29  LL Road Frame - Black, 44        Black      297.6346

In [ ]:
product.sort_values("ProductPrice", ascending=False).head(10)

,ProductKey,ProductSubcategoryKey,ProductSKU,ProductName,ModelName,ProductDescription,ProductColor,ProductSize,ProductStyle,ProductCost,ProductPrice
45,313,2,BK-R93R-52,"Road-150 Red, 52",Road-150,This bike is ridden by race winners. Developed...,Red,52,U,2171.2942,3578.27
42,310,2,BK-R93R-62,"Road-150 Red, 62",Road-150,This bike is ridden by race winners. Developed...,Red,62,U,2171.2942,3578.27
46,314,2,BK-R93R-56,"Road-150 Red, 56",Road-150,This bike is ridden by race winners. Developed...,Red,56,U,2171.2942,3578.27
43,311,2,BK-R93R-44,"Road-150 Red, 44",Road-150,This bike is ridden by race winners. Developed...,Red,44,U,2171.2942,3578.27
44,312,2,BK-R93R-48,"Road-150 Red, 48",Road-150,This bike is ridden by race winners. Developed...,Red,48,U,2171.2942,3578.27
66,346,1,BK-M82S-44,"Mountain-100 Silver, 44",Mountain-100,Top-of-the-line competition mountain bike. Per...,Silver,44,U,1912.1544,3399.99
65,345,1,BK-M82S-42,"Mountain-100 Silver, 42",Mountain-100,Top-of-the-line competition mountain bike. Per...,Silver,42,U,1912.1544,3399.99
67,347,1,BK-M82S-48,"Mountain-100 Silver, 48",Mountain-100,Top-of-the-line competition mountain bike. Per...,Silver,48,U,1912.1544,3399.99
64,344,1,BK-M82S-38,"Mountain-100 Silver, 38",Mountain-100,Top-of-the-line competition mountain bike. Per...,Silver,38,U,1912.1544,3399.99
71,351,1,BK-M82B-48,"Mountain-100 Black, 48",Mountain-100,Top-of-the-line competition mountain bike. Per...,Black,48,U,1898.0944,3374.99

In [ ]:
product.sort_values("ProductPrice", ascending=True).head(10)

,ProductKey,ProductSubcategoryKey,ProductSKU,ProductName,ModelName,ProductDescription,ProductColor,ProductSize,ProductStyle,ProductCost,ProductPrice
166,480,37,PK-7098,Patch Kit/8 Patches,Patch kit,"Includes 8 different size patches, glue and sa...",NaN,0,0,0.8565,2.2900
215,529,37,TT-R982,Road Tire Tube,Road Tire Tube,Conventional all-purpose tube.,NaN,0,0,1.4923,3.9900
216,530,37,TT-T092,Touring Tire Tube,Touring Tire Tube,General purpose tube.,NaN,0,0,1.8663,4.9900
214,528,37,TT-M928,Mountain Tire Tube,Mountain Tire Tube,Self-sealing tube.,NaN,0,0,1.8663,4.9900
163,477,28,WB-H098,Water Bottle - 30 oz.,Water Bottle,AWC logo water bottle - holds 30 oz; leak-proof.,NaN,0,0,1.8663,4.9900
170,484,29,CL-9009,Bike Wash - Dissolver,Bike Wash,Washes off the toughest road grime; dissolves ...,NaN,0,0,2.9733,7.9500
5,223,19,CA-1098,AWC Logo Cap,Cycling Cap,Traditional style with a flip-up brim; one-siz...,Multi,0,U,5.7052,8.6442
168,482,23,SO-R809-L,"Racing Socks, L",Racing Socks,"Thin, lightweight and durable with cuffs that ...",White,L,U,3.3623,8.9900
167,481,23,SO-R809-M,"Racing Socks, M",Racing Socks,"Thin, lightweight and durable with cuffs that ...",White,M,U,3.3623,8.9900
165,479,28,BC-R205,Road Bottle Cage,Road Bottle Cage,Aluminum cage is lighter than our mountain ver...,NaN,0,0,3.3623,8.9900

In [ ]:
customer.sort_values("AnnualIncome", ascending=False).head(10)

,CustomerKey,Prefix,FirstName,LastName,BirthDate,MaritalStatus,Gender,EmailAddress,AnnualIncome,TotalChildren,EducationLevel,Occupation,HomeOwner
6067,17182,MRS.,JESSICA,PATTERSON,1958-05-10,S,F,jessica35@adventure-works.com,170000,2,Bachelors,Management,N
8755,19927,MR.,RUBEN,FERNANDEZ,1954-07-26,M,M,ruben17@adventure-works.com,170000,5,High School,Professional,Y
2283,13327,MRS.,ISABELLE,RUSSELL,1938-07-11,M,F,isabelle18@adventure-works.com,170000,1,Graduate Degree,Management,Y
1296,12318,MS.,KRISTINA,SCHMIDT,1953-05-03,M,F,kristina10@adventure-works.com,170000,0,Bachelors,Management,N
8734,19906,MR.,ARMANDO,MUÑOZ,1956-05-03,M,M,armando7@adventure-works.com,170000,3,High School,Professional,Y
1113,12134,MR.,HECTOR,ALONSO,1955-09-23,M,M,hector6@adventure-works.com,170000,3,High School,Professional,Y
6070,17185,MRS.,KARLA,ANAND,1957-09-21,M,F,karla23@adventure-works.com,170000,4,Partial College,Professional,N
8733,19905,MRS.,CHELSEA,FERNANDEZ,1956-10-21,S,F,chelsea17@adventure-works.com,170000,3,Partial College,Professional,N
9384,20571,MRS.,ALLISON,GRAY,1946-10-12,S,F,allison4@adventure-works.com,170000,4,Bachelors,Management,N
14533,25805,MRS.,MELODY,GOMEZ,1949-05-01,M,F,melody1@adventure-works.com,170000,5,Partial College,Management,N

In [ ]:
sales_2022.sort_values("OrderQuantity", ascending=False).head(10)

,OrderDate,StockDate,OrderNumber,ProductKey,CustomerKey,TerritoryKey,OrderLineItem,OrderQuantity
16067,2022-04-16,2022-01-27,SO68376,478,16127,4,2,3
16062,2022-04-15,2022-02-06,SO68292,529,14611,6,1,3
2340,2022-01-17,2021-09-27,SO62253,529,11277,6,1,3
2344,2022-01-17,2021-10-09,SO62279,223,25975,1,4,3
11908,2022-03-20,2022-01-12,SO66516,480,16341,9,2,3
26885,2022-06-16,2022-04-23,SO73064,223,22537,8,1,3
26886,2022-06-16,2022-03-23,SO73064,477,22537,8,2,3
11903,2022-03-20,2021-12-31,SO66532,528,15053,7,1,3
23085,2022-05-26,2022-04-01,SO71383,480,21490,6,2,3
1381,2022-01-10,2021-09-20,SO61837,462,12198,1,6,3

In [ ]:
product.sort_values(
    by=["ProductColor", "ProductPrice"],
    ascending=[True, False]
).head(20)

,ProductKey,ProductSubcategoryKey,ProductSKU,ProductName,ModelName,ProductDescription,ProductColor,ProductSize,ProductStyle,ProductCost,ProductPrice
68,348,1,BK-M82B-38,"Mountain-100 Black, 38",Mountain-100,Top-of-the-line competition mountain bike. Per...,Black,38,U,1898.0944,3374.9900
69,349,1,BK-M82B-42,"Mountain-100 Black, 42",Mountain-100,Top-of-the-line competition mountain bike. Per...,Black,42,U,1898.0944,3374.9900
70,350,1,BK-M82B-44,"Mountain-100 Black, 44",Mountain-100,Top-of-the-line competition mountain bike. Per...,Black,44,U,1898.0944,3374.9900
71,351,1,BK-M82B-48,"Mountain-100 Black, 48",Mountain-100,Top-of-the-line competition mountain bike. Per...,Black,48,U,1898.0944,3374.9900
86,373,2,BK-R89B-44,"Road-250 Black, 44",Road-250,"Alluminum-alloy frame provides a light, stiff ...",Black,44,U,1320.6838,2181.5625
87,375,2,BK-R89B-48,"Road-250 Black, 48",Road-250,"Alluminum-alloy frame provides a light, stiff ...",Black,48,U,1320.6838,2181.5625
88,377,2,BK-R89B-52,"Road-250 Black, 52",Road-250,"Alluminum-alloy frame provides a light, stiff ...",Black,52,U,1320.6838,2181.5625
89,379,2,BK-R89B-58,"Road-250 Black, 58",Road-250,"Alluminum-alloy frame provides a light, stiff ...",Black,58,U,1320.6838,2181.5625
75,358,1,BK-M68B-38,"Mountain-200 Black, 38",Mountain-200,Serious back-country riding. Perfect for all l...,Black,38,U,1105.8100,2049.0982
76,360,1,BK-M68B-42,"Mountain-200 Black, 42",Mountain-200,Serious back-country riding. Perfect for all l...,Black,42,U,1105.8100,2049.0982
77,362,1,BK-M68B-46,"Mountain-200 Black, 46",Mountain-200,Serious back-country riding. Perfect for all l...,Black,46,U,1105.8100,2049.0982
37,299,12,FR-M94B-44,"HL Mountain Frame - Black, 44",HL Mountain Frame,Each frame is hand-crafted in our Bothell faci...,Black,44,U,699.0928,1349.6000
38,300,12,FR-M94B-48,"HL Mountain Frame - Black, 48",HL Mountain Frame,Each frame is hand-crafted in our Bothell faci...,Black,48,U,699.0928,1349.6000
130,437,14,FR-R92B-62,"HL Road Frame - Black, 62",HL Road Frame,Our lightest and best quality aluminum frame m...,Black,62,U,722.2568,1301.3636
131,439,14,FR-R92B-44,"HL Road Frame - Black, 44",HL Road Frame,Our lightest and best quality aluminum frame m...,Black,44,U,722.2568,1301.3636
132,441,14,FR-R92B-48,"HL Road Frame - Black, 48",HL Road Frame,Our lightest and best quality aluminum frame m...,Black,48,U,722.2568,1301.3636
133,443,14,FR-R92B-52,"HL Road Frame - Black, 52",HL Road Frame,Our lightest and best quality aluminum frame m...,Black,52,U,722.2568,1301.3636
36,296,12,FR-M94B-42,"HL Mountain Frame - Black, 42",HL Mountain Frame,Each frame is hand-crafted in our Bothell faci...,Black,42,U,617.0281,1191.1739
39,301,12,FR-M94B-46,"HL Mountain Frame - Black, 46",HL Mountain Frame,Each frame is hand-crafted in our Bothell faci...,Black,46,U,617.0281,1191.1739
40,304,12,FR-M94B-38,"HL Mountain Frame - Black, 38",HL Mountain Frame,Each frame is hand-crafted in our Bothell faci...,Black,38,U,617.0281,1191.1739

In [ ]:
most_expensive_products = product.sort_values("ProductPrice", ascending=False).head(10)
most_expensive_products.head()

,ProductKey,ProductSubcategoryKey,ProductSKU,ProductName,ModelName,ProductDescription,ProductColor,ProductSize,ProductStyle,ProductCost,ProductPrice
45,313,2,BK-R93R-52,"Road-150 Red, 52",Road-150,This bike is ridden by race winners. Developed...,Red,52,U,2171.2942,3578.27
42,310,2,BK-R93R-62,"Road-150 Red, 62",Road-150,This bike is ridden by race winners. Developed...,Red,62,U,2171.2942,3578.27
46,314,2,BK-R93R-56,"Road-150 Red, 56",Road-150,This bike is ridden by race winners. Developed...,Red,56,U,2171.2942,3578.27
43,311,2,BK-R93R-44,"Road-150 Red, 44",Road-150,This bike is ridden by race winners. Developed...,Red,44,U,2171.2942,3578.27
44,312,2,BK-R93R-48,"Road-150 Red, 48",Road-150,This bike is ridden by race winners. Developed...,Red,48,U,2171.2942,3578.27

In [ ]:
cheapest_products = product.sort_values("ProductPrice", ascending=True).head(10)
cheapest_products.head()

,ProductKey,ProductSubcategoryKey,ProductSKU,ProductName,ModelName,ProductDescription,ProductColor,ProductSize,ProductStyle,ProductCost,ProductPrice
166,480,37,PK-7098,Patch Kit/8 Patches,Patch kit,"Includes 8 different size patches, glue and sa...",NaN,0,0,0.8565,2.29
215,529,37,TT-R982,Road Tire Tube,Road Tire Tube,Conventional all-purpose tube.,NaN,0,0,1.4923,3.99
216,530,37,TT-T092,Touring Tire Tube,Touring Tire Tube,General purpose tube.,NaN,0,0,1.8663,4.99
214,528,37,TT-M928,Mountain Tire Tube,Mountain Tire Tube,Self-sealing tube.,NaN,0,0,1.8663,4.99
163,477,28,WB-H098,Water Bottle - 30 oz.,Water Bottle,AWC logo water bottle - holds 30 oz; leak-proof.,NaN,0,0,1.8663,4.99

In [ ]:
customer.sort_values("AnnualIncome", ascending=False).head(10)

,CustomerKey,Prefix,FirstName,LastName,BirthDate,MaritalStatus,Gender,EmailAddress,AnnualIncome,TotalChildren,EducationLevel,Occupation,HomeOwner
6067,17182,MRS.,JESSICA,PATTERSON,1958-05-10,S,F,jessica35@adventure-works.com,170000,2,Bachelors,Management,N
8755,19927,MR.,RUBEN,FERNANDEZ,1954-07-26,M,M,ruben17@adventure-works.com,170000,5,High School,Professional,Y
2283,13327,MRS.,ISABELLE,RUSSELL,1938-07-11,M,F,isabelle18@adventure-works.com,170000,1,Graduate Degree,Management,Y
1296,12318,MS.,KRISTINA,SCHMIDT,1953-05-03,M,F,kristina10@adventure-works.com,170000,0,Bachelors,Management,N
8734,19906,MR.,ARMANDO,MUÑOZ,1956-05-03,M,M,armando7@adventure-works.com,170000,3,High School,Professional,Y
1113,12134,MR.,HECTOR,ALONSO,1955-09-23,M,M,hector6@adventure-works.com,170000,3,High School,Professional,Y
6070,17185,MRS.,KARLA,ANAND,1957-09-21,M,F,karla23@adventure-works.com,170000,4,Partial College,Professional,N
8733,19905,MRS.,CHELSEA,FERNANDEZ,1956-10-21,S,F,chelsea17@adventure-works.com,170000,3,Partial College,Professional,N
9384,20571,MRS.,ALLISON,GRAY,1946-10-12,S,F,allison4@adventure-works.com,170000,4,Bachelors,Management,N
14533,25805,MRS.,MELODY,GOMEZ,1949-05-01,M,F,melody1@adventure-works.com,170000,5,Partial College,Management,N

In [ ]:
sales_2022.sort_values("OrderQuantity", ascending=False).head(10)

,OrderDate,StockDate,OrderNumber,ProductKey,CustomerKey,TerritoryKey,OrderLineItem,OrderQuantity
16067,2022-04-16,2022-01-27,SO68376,478,16127,4,2,3
16062,2022-04-15,2022-02-06,SO68292,529,14611,6,1,3
2340,2022-01-17,2021-09-27,SO62253,529,11277,6,1,3
2344,2022-01-17,2021-10-09,SO62279,223,25975,1,4,3
11908,2022-03-20,2022-01-12,SO66516,480,16341,9,2,3
26885,2022-06-16,2022-04-23,SO73064,223,22537,8,1,3
26886,2022-06-16,2022-03-23,SO73064,477,22537,8,2,3
11903,2022-03-20,2021-12-31,SO66532,528,15053,7,1,3
23085,2022-05-26,2022-04-01,SO71383,480,21490,6,2,3
1381,2022-01-10,2021-09-20,SO61837,462,12198,1,6,3

In [ ]:
customer.sort_values(
    by=["EducationLevel", "AnnualIncome"],
    ascending=[True, False]
).head(10)

,CustomerKey,Prefix,FirstName,LastName,BirthDate,MaritalStatus,Gender,EmailAddress,AnnualIncome,TotalChildren,EducationLevel,Occupation,HomeOwner
238,11244,MRS.,ALEXIS,COLEMAN,1957-11-26,S,F,alexis28@adventure-works.com,170000,2,Bachelors,Management,N
411,11422,MR.,DUSTIN,DENG,1946-09-01,M,M,dustin1@adventure-works.com,170000,4,Bachelors,Management,Y
1102,12123,MR.,WESLEY,LIANG,1958-06-14,M,M,wesley16@adventure-works.com,170000,2,Bachelors,Management,Y
1296,12318,MS.,KRISTINA,SCHMIDT,1953-05-03,M,F,kristina10@adventure-works.com,170000,0,Bachelors,Management,N
1616,12645,MS.,AUDREY,RUIZ,1953-05-07,M,F,audrey3@adventure-works.com,170000,0,Bachelors,Management,Y
2538,13590,MR.,LOUIS,XIE,1953-05-18,M,M,louis20@adventure-works.com,170000,0,Bachelors,Management,N
2539,13591,MS.,LATASHA,ALONSO,1953-05-25,M,F,latasha8@adventure-works.com,170000,0,Bachelors,Management,Y
3121,14184,MR.,CALEB,JENKINS,1953-10-27,M,M,caleb3@adventure-works.com,170000,0,Bachelors,Management,Y
4266,15354,MR.,COREY,KUMAR,1957-02-07,M,M,corey7@adventure-works.com,170000,3,Bachelors,Management,Y
4607,15699,MR.,JONATHON,HERNANDEZ,1953-09-11,M,M,jonathon0@adventure-works.com,170000,0,Bachelors,Management,Y

In [ ]:
product[["ProductCost", "ProductPrice"]].describe()

       ProductCost  ProductPrice
count   293.000000    293.000000
mean    413.661009    714.437357
std     517.611849    872.157258
min       0.856500      2.290000
25%      31.724400     63.500000
50%     199.375700    333.420000
75%     601.743700   1003.910000
max    2171.294200   3578.270000

In [ ]:
customer["AnnualIncome"].describe()

count     18148.000000
mean      57269.120564
std       32236.535573
min       10000.000000
25%       30000.000000
50%       60000.000000
75%       70000.000000
max      170000.000000
Name: AnnualIncome, dtype: float64

In [ ]:
sales_2022["OrderQuantity"].describe()

count    29481.000000
mean         1.537058
std          0.617249
min          1.000000
25%          1.000000
50%          1.000000
75%          2.000000
max          3.000000
Name: OrderQuantity, dtype: float64

In [ ]:
print("Average product price:", product["ProductPrice"].mean())
print("Minimum product price:", product["ProductPrice"].min())
print("Maximum product price:", product["ProductPrice"].max())
print("Median product price:", product["ProductPrice"].median())

Average product price: 714.43735665529
Minimum product price: 2.29
Maximum product price: 3578.27
Median product price: 333.42

In [ ]:
print("Unique customers:", customer["CustomerKey"].nunique())
print("Unique products:", product["ProductKey"].nunique())
print("Unique customer occupations:", customer["Occupation"].nunique())
print("Unique product colors:", product["ProductColor"].nunique())

Unique customers: 18148
Unique products: 293
Unique customer occupations: 5
Unique product colors: 9

In [ ]:
print("Customer gender:")
print(customer["Gender"].value_counts())

print("\nCustomer occupation:")
print(customer["Occupation"].value_counts())

print("\nProduct color:")
print(product["ProductColor"].value_counts())

Customer gender:
Gender
M    9126
F    8892
Name: count, dtype: int64

Customer occupation:
Occupation
Professional      5424
Skilled Manual    4501
Management        3011
Clerical          2859
Manual            2353
Name: count, dtype: int64

Product color:
ProductColor
Black           88
Red             37
Silver          36
Yellow          36
Blue            26
Multi            8
Silver/Black     7
White            4
Grey             1
Name: count, dtype: int64

In [ ]:
number_of_products = product["ProductKey"].nunique()
print("Number of unique products:", number_of_products)

Number of unique products: 293

In [ ]:
average_product_price = product["ProductPrice"].mean()
print(f"Average product price: ${average_product_price:,.2f}")

Average product price: $714.44

In [ ]:
most_expensive_product = product.loc[product["ProductPrice"].idxmax(),
                                         ["ProductName", "ProductPrice"]]

most_expensive_product

ProductName     Road-150 Red, 62
ProductPrice             3578.27
Name: 42, dtype: object

In [ ]:
cheapest_product = product.loc[product["ProductPrice"].idxmin(),
                                     ["ProductName", "ProductPrice"]]

cheapest_product

ProductName     Patch Kit/8 Patches
ProductPrice                   2.29
Name: 166, dtype: object

In [ ]:
average_income = customer["AnnualIncome"].mean()
print(f"Average annual customer income: ${average_income:,.2f}")

Average annual customer income: $57,269.12

In [ ]:
print("2020 units:", sales_2020["OrderQuantity"].sum())
print("2021 units:", sales_2021["OrderQuantity"].sum())
print("2022 units:", sales_2022["OrderQuantity"].sum())

2020 units: 2630
2021 units: 36230
2022 units: 45314

In [ ]:
print("2020 transactions:", len(sales_2020))
print("2021 transactions:", len(sales_2021))
print("2022 transactions:", len(sales_2022))

2020 transactions: 2630
2021 transactions: 23935
2022 transactions: 29481

In [ ]:
#customer analysis
total_customers = customer["CustomerKey"].nunique()
print("Total customers:", total_customers)

average_income = customer["AnnualIncome"].mean()
print(average_income)

highest_income = customer["AnnualIncome"].max()
print(highest_income)

occupation_counts = customer["Occupation"].value_counts()
most_common_occupation = occupation_counts.idxmax()
print( most_common_occupation)

homeowners_count = (customer["HomeOwner"] == "Y").sum()
print(homeowners_count)

Total customers: 18148
57269.120564249504
170000
Professional
12260

In [ ]:
#Product Analysis

total_products = product["ProductKey"].nunique()
print(total_products)

average_price = product["ProductPrice"].mean()
print(average_price)

highest_price = product["ProductPrice"].max()
print(highest_price)

average_cost = product["ProductCost"].mean()
print(average_cost)

color_counts = product["ProductColor"].value_counts()
most_common_color = color_counts.idxmax()
print(most_common_color)

293
714.43735665529
3578.27
413.6610092150171
Black

In [ ]:
# Sales Analysis
# combine separate years into one single 'sales' dataFrame
sales = pd.concat([sales_2020, sales_2021, sales_2022])

In [ ]:
top_sales_year= sales["OrderDate"].dt.year.value_counts().idxmax()
print(top_sales_year)

top_quantity_year= sales.groupby("OrderDate")["OrderQuantity"].sum()
print(top_quantity_year)

max_quantity_2022 = sales_2022["OrderQuantity"].max()
print(max_quantity_2022)

unique_customers_2022 = sales_2022["CustomerKey"].nunique()
print(unique_customers_2022)

unique_products_2022 = sales_2022["ProductKey"].nunique()
print(unique_products_2022)

2022
OrderDate
2020-01-01      4
2020-01-02      4
2020-01-03      8
2020-01-04      5
2020-01-05      3
             ...
2022-06-26    292
2022-06-27    269
2022-06-28    328
2022-06-29    258
2022-06-30    214
Name: OrderQuantity, Length: 911, dtype: int64
3
10502
102

In [ ]:
# Data Quality

duplicate_rows = customer.duplicated().sum()
print(duplicate_rows)

missing_values = product.isnull().sum()
print(missing_values)

[sales_2020.columns.to_list(), sales_2021.columns.to_list(), sales_2022.columns.to_list()]
sales_2021.dtypes

order_date_dtype = sales_2021["OrderDate"].dtype
print(order_date_dtype)

0
ProductKey                0
ProductSubcategoryKey     0
ProductSKU                0
ProductName               0
ModelName                 0
ProductDescription        0
ProductColor             50
ProductSize               0
ProductStyle              0
ProductCost               0
ProductPrice              0
dtype: int64
datetime64[ns]

# Observation
 In customer analysis the highest annual income in the dataset is 170000 while the average annual income from all customers is 57269.120564249504

 In product analysis the most frequent occuring products color is black while the average product price sits at 714.43735665529

 In sales analysis the year 2022 has the highest number of ov overall sales transactions